In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r"C:\Users\apisr\Downloads\Teen_Mental_Health_Dataset.csv")

In [ ]:
#data exploration

In [11]:
print("\n First 5 values")
df.head()

 First 5 values

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [12]:
df.tail()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [13]:
print("\n Dataset shape")
df.shape

 Dataset shape

(1200, 13)

In [15]:
print("Column names")
df.columns

Column names

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='str')

In [16]:
print("Data-types")
df.dtypes

Data-types

age                           int64
gender                          str
daily_social_media_hours    float64
platform_usage                  str
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level        str
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

In [17]:
print("Dataset info")
df.info()

Dataset info
<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 122.0 KB

In [18]:
print("Statistical Summary")
df.describe()

Statistical Summary

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

In [19]:
print("missing values")
print(df.isnull().sum())

missing values
age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [ ]:
#data  preprocessing

print("\n Duplicate rows: ", df.duplicated().sum())

 Duplicate rows:  0

In [ ]:
#if there are any dups remove using
df=df.drop_duplicates()

In [20]:
#Fill missing values if its there 
num_cols=df.select_dtypes(include=np.number).columns
df[num_cols]

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,3,4,4,0
1196,16,2.3,8.0,1.9,2.12,0.4,7,4,4,0
1197,14,1.7,8.7,0.7,3.98,0.8,1,1,1,0
1198,15,3.9,8.5,2.1,3.19,0.6,7,9,9,0
1199,16,4.7,6.5,1.0,2.91,0.9,5,7,3,0

In [ ]:
for cols in num_cols:
    df[cols] = df[cols].fillna(df[cols].mean())

In [9]:
cat_cols = df.select_dtypes(include='object').columns

C:\Users\apisr\AppData\Local\Temp\ipykernel_30224\2176772794.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

In [10]:
for cols in cat_cols:
    df[cols] = df[cols].fillna(df[cols].mode()[0])

In [21]:
print("\n Missing values after cleaning")
print(df.isnull().sum())

 Missing values after cleaning
age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [23]:
#visualisation
platform_counts=df['platform_usage'].value_counts()

In [ ]:
plt.figure()

In [ ]:
#histogram- frequency distribution
plt.figure(figsize=(6,5))
plt.hist(df['sleep_hours'],bins=15)